# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 17:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=2000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UrlComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=2000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UrlPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlmessage', models.URLField()),
                ('urlintroduce', models.CharField(max_length=100)),
                ('urlpublish_time', models.DateTimeField(auto_now_add=True)),
                ('urlreadcount', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-urlpublish_time'],
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_rank_score', models.IntegerField(default=0)),
                ('user_create_date', models.DateField(auto_now_add=True)),
                ('user_profile', models.ImageField(default=b'C:/Users/26223/Desktop/django/Wall/media\\images\\generic_profile_photo.jpg', null=True, upload_to=b'img')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_class', models.IntegerField()),
            ],
            options={
                'ordering': ['user_rank_score', 'user_create_date'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='urlpublish',
            name='username',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='FundPart.UserList'),
        ),
        migrations.AddField(
            model_name='urlcomment',
            name='comment1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundPart.UrlPublish'),
        ),
        migrations.AddField(
            model_name='urlcomment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundPart.UserList'),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='comment2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundPart.UrlComment'),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundPart.UserList'),
        ),
    ]
